spring:
  application:
    name: hhplus_02_clean_architecture

  sql:
    init: # application ??? sql ??
      mode: always
      data-locations: classpath*:db/data.sql
      continue-on-error: true

# JPA ??
jpa:
  hibernate:
    ddl-auto: create # DB ??? ?? (none, create, create-drop, update, validate)
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true # ?? ?? ?? (??)
      show_sql: true # ?? ?? ??
  defer-datasource-initialization: true