spring:
  application:
    name: hhplus_02_clean_architecture

  datasource:
    url: jdbc:mysql://localhost:3307/mysqldb
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init: # application 실행시 sql 실행
      mode: always
      data-locations: classpath*:init-scripts/data.sql # resources 안에 위치해야 함
      continue-on-error: true

# JPA ??
  jpa:
    hibernate:
      ddl-auto: create # DB ??? ?? (none, create, create-drop, update, validate)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true